version: '3.8'

services:
  slack_db:
    container_name: slack_db
    image: mysql:5.7
    volumes:
      - ./mysql:/var/lib/mysql
    ports:
      - '3307:3306'
    restart: always
    command: --default-authentication-plugin=mysql_native_password --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci
    environment:
      - MYSQL_ROOT_PASSWORD=1234
      - MYSQL_DATABASE=slack_rdb_local
      - MYSQL_USER=swd
      - MYSQL_PASSWORD=1234

  slack_api:
    container_name: slack_api
    working_dir: /slack_backend
    build:
      context: .
      dockerfile: ./Dockerfile
    env_file:
      - .env
    command: npm run start:dev
    volumes:
      - .:/slack_backend
      - ./npmlog:/root/.npm/_logs
    ports:
      - '3000:3000'
    restart: always
    depends_on:
      - slack_db
