version: '3.8'

services:
  database:
    container_name: slack_db
    image: slack_db:latest
    platform: linux/x86_64
    build:
      context: .
      cache_from:
        - slack_db:latest
      dockerfile: ./database.Dockerfile
    volumes:
      - ./mysql:/var/lib/mysql
    ports:
      - '3308:3306'


  server:
    container_name: slack_api
    image: slack_api:latest
    build:
      context: .
      cache_from:
        - slack_api:latest
      dockerfile: server-dev.Dockerfile
    env_file:
      - .env
    ports:
      - '8080:3000'
    depends_on:
      - database
    command:
      - bash
      - -c
      - |
        /server/wait-for-it.sh database:3306 -t 10
        npm run start:dev
    volumes:
      - .:/server
      - ./npmlog:/root/.npm/_logs
